### Check all clubs
GET http://localhost:8080/clubs
Authorization: Basic admin:password

### Create a new club, please add a PlayerProfile 
### to admin in PlayerTest.http first
POST http://localhost:8080/clubs
Authorization: Basic admin:password
Content-Type: application/json

{
  "club": {
    "name": "My New Club",
    "elo": 1000,
    "ratingDeviation": 50
  },
  "creatorId": 1  
}

### Get a specific club by ID
GET http://localhost:8080/clubs/1
Authorization: Basic admin:password

### Apply to a club
POST http://localhost:8080/clubs/1/apply
Authorization: Basic admin:password
Content-Type: application/json

{
  "desiredPosition": "POSITION_FORWARD"
}
