### Check admin user exists, and playerProfile is null
GET http://localhost:8080/users
Authorization: Basic admin password

### Add player profile to admin
POST http://localhost:8080/users/1/playerProfile
Authorization: Basic admin password
Content-Type: application/json

{
    "preferredPosition": "POSITION_FORWARD",
    "profileDescription": "I love football!"
}

### Add player profile to normal user
POST http://localhost:8080/users/1/playerProfile
Authorization: Basic admin password
Content-Type: application/json

{
    "preferredPosition": "POSITION_DEFENDER",
    "profileDescription": "I love football too!"
}

### Update PlayerPostion
PUT http://localhost:8080/users/1/playerProfile/position
Authorization: Basic admin password
Content-Type: application/json

{
    "preferredPosition": "POSITION_MIDFIELDER"
}